# Generated by Django 4.2.4 on 2023-08-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('alive', 'ALIVE'), ('dead', 'DEAD'), ('unknown', 'UNKNOWN')], max_length=50, null=True)),
                ('species', models.CharField(max_length=150)),
                ('chraterType', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'fem'), ('others', 'others')], max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
