# Generated by Django 4.2.4 on 2023-08-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('locationType', models.CharField(choices=[('planet', 'planet'), ('cluster', 'cluster'), ('space_station', 'space_station'), ('microverse', 'microverse'), ('tv', 'tv')], max_length=100, null=True)),
                ('dimension', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
