# Generated by Django 4.2.4 on 2023-08-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locationType',
            field=models.CharField(choices=[('PLANET', 'planet'), ('cluster', 'cluster'), ('space_station', 'space_station'), ('microverse', 'microverse'), ('tv', 'tv')], max_length=100, null=True),
        ),
    ]
