# Generated by Django 4.2.4 on 2023-08-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_location_locationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locationType',
            field=models.CharField(choices=[('planet', 'PLANET'), ('cluster', 'CLUSTER'), ('space_station', 'SPACE STATION'), ('microverse', 'MICROVERSE'), ('tv', 'tv')], max_length=100, null=True),
        ),
    ]
