# Generated by Django 4.2.4 on 2023-08-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_location_dimension_alter_location_locationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='chraterType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEM'), ('others', 'OTHERS')], max_length=50, null=True),
        ),
    ]
