# Generated by Django 4.2.4 on 2023-08-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_character_chratertype_alter_character_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='chraterType',
            field=models.CharField(choices=[('human', 'HUMAN'), ('alien', 'ALIEN')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEM'), ('others', 'OTHERS')], max_length=50, null=True),
        ),
    ]
