# Generated by Django 4.2.4 on 2023-08-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_character_chratertype_character_charatertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='charaterType',
            field=models.CharField(choices=[('genetic_experiment', 'GENETIC EXPERIMENT'), ('Superhuman (Ghost trains summoner)', 'SUPERHUMAN'), ('parasite', 'PARASITE')], max_length=50, null=True),
        ),
    ]
