# Generated by Django 4.2.4 on 2023-08-23 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_character_charatertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='main.location'),
        ),
        migrations.AlterField(
            model_name='character',
            name='charaterType',
            field=models.CharField(blank=True, choices=[('genetic_experiment', 'GENETIC EXPERIMENT'), ('Superhuman (Ghost trains summoner)', 'SUPERHUMAN'), ('parasite', 'PARASITE')], max_length=50, null=True),
        ),
    ]
