# Generated by Django 4.2.4 on 2023-08-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_character_species_alter_character_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locationType',
            field=models.CharField(blank=True, choices=[('planet', 'PLANET'), ('cluster', 'CLUSTER'), ('space_station', 'SPACE STATION'), ('microverse', 'MICROVERSE'), ('tv', 'TV'), ('resort', 'RESORT'), ('fantasy_town', 'FANTASY TOWN'), ('dream', 'DREAM')], max_length=100, null=True),
        ),
    ]
